// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: IdentityServer4Service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GPS.IdentityServer4GrpcServiceBase {

  /// <summary>Holder for reflection information generated from IdentityServer4Service.proto</summary>
  public static partial class IdentityServer4ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for IdentityServer4Service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IdentityServer4ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxJZGVudGl0eVNlcnZlcjRTZXJ2aWNlLnByb3RvEiJHUFMuSWRlbnRpdHlT",
            "ZXJ2ZXI0R3JwY1NlcnZpY2VCYXNlGhFSZXN1bHRSZXBseS5wcm90byKtAQoU",
            "R2VuZXJhdGVUb2tlblJlcXVlc3QSVAoGQ2xhaW1zGAEgAygLMkQuR1BTLklk",
            "ZW50aXR5U2VydmVyNEdycGNTZXJ2aWNlQmFzZS5HZW5lcmF0ZVRva2VuUmVx",
            "dWVzdC5DbGFpbXNFbnRyeRIQCghJbnRlcnZhbBgCIAEoBRotCgtDbGFpbXNF",
            "bnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIloKEkdlbmVy",
            "YXRlVG9rZW5SZXBseRINCgVUb2tlbhgBIAEoCRI1CgtSZXN1bHRSZXBseRgC",
            "IAEoCzIgLkdQUy5TZXJ2aWNlR3JwY0Jhc2UuUmVzdWx0UmVwbHkiIwoSVmVy",
            "aWZ5VG9rZW5SZXF1ZXN0Eg0KBVRva2VuGAEgASgJIpECChBWZXJpZnlUb2tl",
            "blJlcGx5ElAKBkNsYWltcxgBIAMoCzJALkdQUy5JZGVudGl0eVNlcnZlcjRH",
            "cnBjU2VydmljZUJhc2UuVmVyaWZ5VG9rZW5SZXBseS5DbGFpbXNFbnRyeRJF",
            "CgpSZXN1bHRDb2RlGAIgASgOMjEuR1BTLklkZW50aXR5U2VydmVyNEdycGNT",
            "ZXJ2aWNlQmFzZS5Kd3RSZXN1bHRDb2RlEjUKC1Jlc3VsdFJlcGx5GAMgASgL",
            "MiAuR1BTLlNlcnZpY2VHcnBjQmFzZS5SZXN1bHRSZXBseRotCgtDbGFpbXNF",
            "bnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIiQKE1JlZnJl",
            "c2hUb2tlblJlcXVlc3QSDQoFVG9rZW4YASABKAkioAEKEVJlZnJlc2hUb2tl",
            "blJlcGx5Eg0KBVRva2VuGAEgASgJEkUKClJlc3VsdENvZGUYAiABKA4yMS5H",
            "UFMuSWRlbnRpdHlTZXJ2ZXI0R3JwY1NlcnZpY2VCYXNlLkp3dFJlc3VsdENv",
            "ZGUSNQoLUmVzdWx0UmVwbHkYAyABKAsyIC5HUFMuU2VydmljZUdycGNCYXNl",
            "LlJlc3VsdFJlcGx5Kk8KDUp3dFJlc3VsdENvZGUSBgoCT2sQABIQCgxUb2tl",
            "bkV4cGlyZXMQARIZChVUb2tlbkludmFsaWRTaWduYXR1cmUQAhIJCgVFcnJv",
            "chAJMqQDChpJZGVudGl0eVNlcnZlcjRTZXJ2aWNlR3JwYxKDAQoNR2VuZXJh",
            "dGVUb2tlbhI4LkdQUy5JZGVudGl0eVNlcnZlcjRHcnBjU2VydmljZUJhc2Uu",
            "R2VuZXJhdGVUb2tlblJlcXVlc3QaNi5HUFMuSWRlbnRpdHlTZXJ2ZXI0R3Jw",
            "Y1NlcnZpY2VCYXNlLkdlbmVyYXRlVG9rZW5SZXBseSIAEn0KC1ZlcmlmeVRv",
            "a2VuEjYuR1BTLklkZW50aXR5U2VydmVyNEdycGNTZXJ2aWNlQmFzZS5WZXJp",
            "ZnlUb2tlblJlcXVlc3QaNC5HUFMuSWRlbnRpdHlTZXJ2ZXI0R3JwY1NlcnZp",
            "Y2VCYXNlLlZlcmlmeVRva2VuUmVwbHkiABKAAQoMUmVmcmVzaFRva2VuEjcu",
            "R1BTLklkZW50aXR5U2VydmVyNEdycGNTZXJ2aWNlQmFzZS5SZWZyZXNoVG9r",
            "ZW5SZXF1ZXN0GjUuR1BTLklkZW50aXR5U2VydmVyNEdycGNTZXJ2aWNlQmFz",
            "ZS5SZWZyZXNoVG9rZW5SZXBseSIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GPS.ServiceGrpcBase.ResultReplyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GPS.IdentityServer4GrpcServiceBase.JwtResultCode), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GPS.IdentityServer4GrpcServiceBase.GenerateTokenRequest), global::GPS.IdentityServer4GrpcServiceBase.GenerateTokenRequest.Parser, new[]{ "Claims", "Interval" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::GPS.IdentityServer4GrpcServiceBase.GenerateTokenReply), global::GPS.IdentityServer4GrpcServiceBase.GenerateTokenReply.Parser, new[]{ "Token", "ResultReply" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GPS.IdentityServer4GrpcServiceBase.VerifyTokenRequest), global::GPS.IdentityServer4GrpcServiceBase.VerifyTokenRequest.Parser, new[]{ "Token" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GPS.IdentityServer4GrpcServiceBase.VerifyTokenReply), global::GPS.IdentityServer4GrpcServiceBase.VerifyTokenReply.Parser, new[]{ "Claims", "ResultCode", "ResultReply" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::GPS.IdentityServer4GrpcServiceBase.RefreshTokenRequest), global::GPS.IdentityServer4GrpcServiceBase.RefreshTokenRequest.Parser, new[]{ "Token" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GPS.IdentityServer4GrpcServiceBase.RefreshTokenReply), global::GPS.IdentityServer4GrpcServiceBase.RefreshTokenReply.Parser, new[]{ "Token", "ResultCode", "ResultReply" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum JwtResultCode {
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("Ok")] Ok = 0,
    /// <summary>
    /// token过期
    /// </summary>
    [pbr::OriginalName("TokenExpires")] TokenExpires = 1,
    /// <summary>
    /// token签名错误
    /// </summary>
    [pbr::OriginalName("TokenInvalidSignature")] TokenInvalidSignature = 2,
    /// <summary>
    /// token错误
    /// </summary>
    [pbr::OriginalName("Error")] Error = 9,
  }

  #endregion

  #region Messages
  public sealed partial class GenerateTokenRequest : pb::IMessage<GenerateTokenRequest> {
    private static readonly pb::MessageParser<GenerateTokenRequest> _parser = new pb::MessageParser<GenerateTokenRequest>(() => new GenerateTokenRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GenerateTokenRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GPS.IdentityServer4GrpcServiceBase.IdentityServer4ServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenerateTokenRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenerateTokenRequest(GenerateTokenRequest other) : this() {
      claims_ = other.claims_.Clone();
      interval_ = other.interval_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenerateTokenRequest Clone() {
      return new GenerateTokenRequest(this);
    }

    /// <summary>Field number for the "Claims" field.</summary>
    public const int ClaimsFieldNumber = 1;
    private static readonly pbc::MapField<string, string>.Codec _map_claims_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 10);
    private readonly pbc::MapField<string, string> claims_ = new pbc::MapField<string, string>();
    /// <summary>
    /// 附加信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Claims {
      get { return claims_; }
    }

    /// <summary>Field number for the "Interval" field.</summary>
    public const int IntervalFieldNumber = 2;
    private int interval_;
    /// <summary>
    /// 时间间隔 默认为（7天）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Interval {
      get { return interval_; }
      set {
        interval_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GenerateTokenRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GenerateTokenRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Claims.Equals(other.Claims)) return false;
      if (Interval != other.Interval) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Claims.GetHashCode();
      if (Interval != 0) hash ^= Interval.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      claims_.WriteTo(output, _map_claims_codec);
      if (Interval != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Interval);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += claims_.CalculateSize(_map_claims_codec);
      if (Interval != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Interval);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GenerateTokenRequest other) {
      if (other == null) {
        return;
      }
      claims_.Add(other.claims_);
      if (other.Interval != 0) {
        Interval = other.Interval;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            claims_.AddEntriesFrom(input, _map_claims_codec);
            break;
          }
          case 16: {
            Interval = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GenerateTokenReply : pb::IMessage<GenerateTokenReply> {
    private static readonly pb::MessageParser<GenerateTokenReply> _parser = new pb::MessageParser<GenerateTokenReply>(() => new GenerateTokenReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GenerateTokenReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GPS.IdentityServer4GrpcServiceBase.IdentityServer4ServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenerateTokenReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenerateTokenReply(GenerateTokenReply other) : this() {
      token_ = other.token_;
      ResultReply = other.resultReply_ != null ? other.ResultReply.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenerateTokenReply Clone() {
      return new GenerateTokenReply(this);
    }

    /// <summary>Field number for the "Token" field.</summary>
    public const int TokenFieldNumber = 1;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ResultReply" field.</summary>
    public const int ResultReplyFieldNumber = 2;
    private global::GPS.ServiceGrpcBase.ResultReply resultReply_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GPS.ServiceGrpcBase.ResultReply ResultReply {
      get { return resultReply_; }
      set {
        resultReply_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GenerateTokenReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GenerateTokenReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Token != other.Token) return false;
      if (!object.Equals(ResultReply, other.ResultReply)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (resultReply_ != null) hash ^= ResultReply.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (resultReply_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ResultReply);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (resultReply_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResultReply);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GenerateTokenReply other) {
      if (other == null) {
        return;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.resultReply_ != null) {
        if (resultReply_ == null) {
          resultReply_ = new global::GPS.ServiceGrpcBase.ResultReply();
        }
        ResultReply.MergeFrom(other.ResultReply);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
          case 18: {
            if (resultReply_ == null) {
              resultReply_ = new global::GPS.ServiceGrpcBase.ResultReply();
            }
            input.ReadMessage(resultReply_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class VerifyTokenRequest : pb::IMessage<VerifyTokenRequest> {
    private static readonly pb::MessageParser<VerifyTokenRequest> _parser = new pb::MessageParser<VerifyTokenRequest>(() => new VerifyTokenRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VerifyTokenRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GPS.IdentityServer4GrpcServiceBase.IdentityServer4ServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VerifyTokenRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VerifyTokenRequest(VerifyTokenRequest other) : this() {
      token_ = other.token_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VerifyTokenRequest Clone() {
      return new VerifyTokenRequest(this);
    }

    /// <summary>Field number for the "Token" field.</summary>
    public const int TokenFieldNumber = 1;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VerifyTokenRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VerifyTokenRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Token != other.Token) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VerifyTokenRequest other) {
      if (other == null) {
        return;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class VerifyTokenReply : pb::IMessage<VerifyTokenReply> {
    private static readonly pb::MessageParser<VerifyTokenReply> _parser = new pb::MessageParser<VerifyTokenReply>(() => new VerifyTokenReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VerifyTokenReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GPS.IdentityServer4GrpcServiceBase.IdentityServer4ServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VerifyTokenReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VerifyTokenReply(VerifyTokenReply other) : this() {
      claims_ = other.claims_.Clone();
      resultCode_ = other.resultCode_;
      ResultReply = other.resultReply_ != null ? other.ResultReply.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VerifyTokenReply Clone() {
      return new VerifyTokenReply(this);
    }

    /// <summary>Field number for the "Claims" field.</summary>
    public const int ClaimsFieldNumber = 1;
    private static readonly pbc::MapField<string, string>.Codec _map_claims_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 10);
    private readonly pbc::MapField<string, string> claims_ = new pbc::MapField<string, string>();
    /// <summary>
    /// 附加信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Claims {
      get { return claims_; }
    }

    /// <summary>Field number for the "ResultCode" field.</summary>
    public const int ResultCodeFieldNumber = 2;
    private global::GPS.IdentityServer4GrpcServiceBase.JwtResultCode resultCode_ = 0;
    /// <summary>
    /// 返回状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GPS.IdentityServer4GrpcServiceBase.JwtResultCode ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    /// <summary>Field number for the "ResultReply" field.</summary>
    public const int ResultReplyFieldNumber = 3;
    private global::GPS.ServiceGrpcBase.ResultReply resultReply_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GPS.ServiceGrpcBase.ResultReply ResultReply {
      get { return resultReply_; }
      set {
        resultReply_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VerifyTokenReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VerifyTokenReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Claims.Equals(other.Claims)) return false;
      if (ResultCode != other.ResultCode) return false;
      if (!object.Equals(ResultReply, other.ResultReply)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Claims.GetHashCode();
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      if (resultReply_ != null) hash ^= ResultReply.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      claims_.WriteTo(output, _map_claims_codec);
      if (ResultCode != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ResultCode);
      }
      if (resultReply_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ResultReply);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += claims_.CalculateSize(_map_claims_codec);
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResultCode);
      }
      if (resultReply_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResultReply);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VerifyTokenReply other) {
      if (other == null) {
        return;
      }
      claims_.Add(other.claims_);
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      if (other.resultReply_ != null) {
        if (resultReply_ == null) {
          resultReply_ = new global::GPS.ServiceGrpcBase.ResultReply();
        }
        ResultReply.MergeFrom(other.ResultReply);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            claims_.AddEntriesFrom(input, _map_claims_codec);
            break;
          }
          case 16: {
            resultCode_ = (global::GPS.IdentityServer4GrpcServiceBase.JwtResultCode) input.ReadEnum();
            break;
          }
          case 26: {
            if (resultReply_ == null) {
              resultReply_ = new global::GPS.ServiceGrpcBase.ResultReply();
            }
            input.ReadMessage(resultReply_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class RefreshTokenRequest : pb::IMessage<RefreshTokenRequest> {
    private static readonly pb::MessageParser<RefreshTokenRequest> _parser = new pb::MessageParser<RefreshTokenRequest>(() => new RefreshTokenRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RefreshTokenRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GPS.IdentityServer4GrpcServiceBase.IdentityServer4ServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefreshTokenRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefreshTokenRequest(RefreshTokenRequest other) : this() {
      token_ = other.token_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefreshTokenRequest Clone() {
      return new RefreshTokenRequest(this);
    }

    /// <summary>Field number for the "Token" field.</summary>
    public const int TokenFieldNumber = 1;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RefreshTokenRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RefreshTokenRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Token != other.Token) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RefreshTokenRequest other) {
      if (other == null) {
        return;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RefreshTokenReply : pb::IMessage<RefreshTokenReply> {
    private static readonly pb::MessageParser<RefreshTokenReply> _parser = new pb::MessageParser<RefreshTokenReply>(() => new RefreshTokenReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RefreshTokenReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GPS.IdentityServer4GrpcServiceBase.IdentityServer4ServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefreshTokenReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefreshTokenReply(RefreshTokenReply other) : this() {
      token_ = other.token_;
      resultCode_ = other.resultCode_;
      ResultReply = other.resultReply_ != null ? other.ResultReply.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefreshTokenReply Clone() {
      return new RefreshTokenReply(this);
    }

    /// <summary>Field number for the "Token" field.</summary>
    public const int TokenFieldNumber = 1;
    private string token_ = "";
    /// <summary>
    /// 附加信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ResultCode" field.</summary>
    public const int ResultCodeFieldNumber = 2;
    private global::GPS.IdentityServer4GrpcServiceBase.JwtResultCode resultCode_ = 0;
    /// <summary>
    /// 返回状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GPS.IdentityServer4GrpcServiceBase.JwtResultCode ResultCode {
      get { return resultCode_; }
      set {
        resultCode_ = value;
      }
    }

    /// <summary>Field number for the "ResultReply" field.</summary>
    public const int ResultReplyFieldNumber = 3;
    private global::GPS.ServiceGrpcBase.ResultReply resultReply_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GPS.ServiceGrpcBase.ResultReply ResultReply {
      get { return resultReply_; }
      set {
        resultReply_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RefreshTokenReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RefreshTokenReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Token != other.Token) return false;
      if (ResultCode != other.ResultCode) return false;
      if (!object.Equals(ResultReply, other.ResultReply)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (ResultCode != 0) hash ^= ResultCode.GetHashCode();
      if (resultReply_ != null) hash ^= ResultReply.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (ResultCode != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ResultCode);
      }
      if (resultReply_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ResultReply);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (ResultCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResultCode);
      }
      if (resultReply_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResultReply);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RefreshTokenReply other) {
      if (other == null) {
        return;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.ResultCode != 0) {
        ResultCode = other.ResultCode;
      }
      if (other.resultReply_ != null) {
        if (resultReply_ == null) {
          resultReply_ = new global::GPS.ServiceGrpcBase.ResultReply();
        }
        ResultReply.MergeFrom(other.ResultReply);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
          case 16: {
            resultCode_ = (global::GPS.IdentityServer4GrpcServiceBase.JwtResultCode) input.ReadEnum();
            break;
          }
          case 26: {
            if (resultReply_ == null) {
              resultReply_ = new global::GPS.ServiceGrpcBase.ResultReply();
            }
            input.ReadMessage(resultReply_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
